
export enum OrderStatus {
    PENDING='PENDING',
    ASSIGNED='ASSIGNED',
    PICKED_UP='PICKED_UP',
    DELIVERING='DELIVERING',
    DELIVERED='DELIVERED',
    FAILED='FAILED',
    CANCELLED='CANCELLED',
}